// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package models

type Cathegory struct {
	ID   int64
	Name string
}

type Event struct {
	ID          int64
	Name        string
	Description string
	Cathegory   interface{}
	Time        interface{}
}
