// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: querries.sql

package models

import (
	"context"
)

const deleteEvent = `-- name: DeleteEvent :exec
DELETE FROM event WHERE id = ?
`

func (q *Queries) DeleteEvent(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteEvent, id)
	return err
}

const getCathegorys = `-- name: GetCathegorys :many
SELECT id, name FROM cathegory
`

func (q *Queries) GetCathegorys(ctx context.Context) ([]Cathegory, error) {
	rows, err := q.db.QueryContext(ctx, getCathegorys)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Cathegory
	for rows.Next() {
		var i Cathegory
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEvents = `-- name: GetEvents :many
SELECT id, name, description, cathegory, time FROM event
`

func (q *Queries) GetEvents(ctx context.Context) ([]Event, error) {
	rows, err := q.db.QueryContext(ctx, getEvents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Cathegory,
			&i.Time,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUpcomingEvents = `-- name: GetUpcomingEvents :many
SELECT id, name, description, cathegory, time FROM event WHERE time > CURRENT_TIMESTAMP
`

func (q *Queries) GetUpcomingEvents(ctx context.Context) ([]Event, error) {
	rows, err := q.db.QueryContext(ctx, getUpcomingEvents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Cathegory,
			&i.Time,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const newCathegory = `-- name: NewCathegory :one
INSERT INTO cathegory (name)
VALUES (?) RETURNING id
`

func (q *Queries) NewCathegory(ctx context.Context, name string) (int64, error) {
	row := q.db.QueryRowContext(ctx, newCathegory, name)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const newEvent = `-- name: NewEvent :one
INSERT INTO event (name, description, cathegory, time)
VALUES (?, ?, (SELECT id FROM cathegory WHERE cathegory.name = ?), ?) RETURNING id
`

type NewEventParams struct {
	Name        string
	Description string
	Name_2      string
	Time        interface{}
}

func (q *Queries) NewEvent(ctx context.Context, arg NewEventParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, newEvent,
		arg.Name,
		arg.Description,
		arg.Name_2,
		arg.Time,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}
